[package]
name = "yart"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
approx = "0.5"
impl_ops = "0.1.1"
yaml-rust = "0.4"
image = "0.24"
rand = "0.8"
itertools = "0.10"
